#!/usr/bin/env bash
#
# Homebrew
#
# This installs some of the common dependencies needed (or at least desired)
# using Homebrew.

# Check for Homebrew
if test ! $(which brew)
then
  echo "  Installing Homebrew for you."
  ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)" > /tmp/homebrew-install.log
fi

# Install homebrew packages
brew tap caskroom/versions
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap phinze/cask
brew tap thoughtbot/formulae

brew install brew-cask               
brew install coreutils
brew install curl                    
brew install git                     
brew install grep                    
brew install htop-osx                
brew install the_silver_searcher
brew install watch
brew install wget
brew install zsh
brew install zsh-completions

brew cask install adium
brew cask install alfred
brew cask install caffeine
brew cask install dropbox
brew cask install evernote
brew cask install firefox
brew cask install flash
brew cask install flux
brew cask install google-chrome
brew cask install google-drive
brew cask install iterm2
brew cask install java7
brew cask install keka
brew cask install mysqlworkbench
brew cask install onepassword
brew cask install sequel-pro
brew cask install skitch
brew cask install spectacle
brew cask install sublime-text3
brew cask install transmission
brew cask install vlc

exit 0
